default: &default
  title: Campo
  host: "localhost:3000"

  admin_emails:
    # - admin@example.com

  mailer:
    # For localhost postfix
    smtp_settings:
      address: "localhost:3000"
      port: 25
      enable_starttls_auto: false
      #domain:
      #user_name:
      #password:
      #authentication:
    default_options:
      from: no-reply@example.com
    default_url_options:
      host: "localhost:3000"

  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
