default: &default
  name: Campo
  host: localhost

  mailer:
    default_from: 'no-reply@example.com'

  admin_emails:
    # - admin@example.com

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
